from typing import List, Tuple, Optional
from cgrad.tensor.Tensorwrapper import Tensor

def randn(shape: List[int] | Tuple[int], require_grad:Optional[bool]) -> Tensor: ...
def rand(shape: List[int] | Tuple[int], require_grad:Optional[bool], min:Optional[int], max:Optional[int]) -> Tensor: ...

