from typing import List, Tuple, Optional
import numpy as np

class Tensor:
    def __init__(self, data: List[float] | List[int] | int| float) -> None: ...
    def item(self) -> List[float]: ...
    def shape(self) -> Tuple[int]: ...
    def ndim(self) -> int: ...
    
    def add(self, other:Tensor) -> Tensor: ...
    def sub(self, other:Tensor) -> Tensor: ...
    def mul(self, other:Tensor) -> Tensor: ...
    def div(self, other:Tensor) -> Tensor: ...
    def pow(self, other:Tensor) -> Tensor: ...
    